/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function MerchWhite(props) {
  const { nodes, materials } = useGLTF("/cr24tee1.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StitchMatShape_132157001.geometry}
        material={materials["Material109415.001"]}
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StitchMatShape_130909001.geometry}
        material={materials["Material109415.001"]}
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StitchMatShape_130648001.geometry}
        material={materials["Material109415.001"]}
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StitchMatShape_130377001.geometry}
        material={materials["Material109415.003"]}
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StitchMatShape_129132001.geometry}
        material={materials["Material109415.001"]}
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StitchMatShape_128590001.geometry}
        material={materials["Material109415.001"]}
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StitchMatShape_127574001.geometry}
        material={materials["Material109415.001"]}
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      />
      <group
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pattern2D_4491756001_1.geometry}
          material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pattern2D_4491756001_2.geometry}
          material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pattern2D_4491756001_3.geometry}
          material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.011"]}
        />
      </group>
      <group
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pattern2D_4474558001_1.geometry}
          material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pattern2D_4474558001_2.geometry}
          material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pattern2D_4474558001_3.geometry}
          material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.011"]}
        />
      </group>
      <group
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pattern2D_2949190001_1.geometry}
          material={materials.Knit_Fleece_Terry_FRONT_109192}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pattern2D_2949190001_2.geometry}
          material={materials["Knit_Fleece_Terry_FRONT_109192.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pattern2D_2949190001_3.geometry}
          material={materials["Knit_Fleece_Terry_FRONT_109192.002"]}
        />
      </group>
      <group
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["71001_1"].geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["71001_2"].geometry}
          material={materials["fuzz.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["71001_3"].geometry}
          material={materials["Knit_Fleece_Terry_FRONT_109192.014"]}
        />
      </group>
      <group
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["70001_1"].geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["70001_2"].geometry}
          material={materials.fuzz}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["70001_3"].geometry}
          material={materials["Knit_Fleece_Terry_FRONT_109192.017"]}
        />
      </group>
      <group
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["64001_1"].geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["64001_2"].geometry}
          material={materials.fuzz}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["64001_3"].geometry}
          material={materials["Knit_Fleece_Terry_FRONT_109192.017"]}
        />
      </group>
      <group
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["31001_1"].geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["31001_2"].geometry}
          material={materials.fuzz}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["31001_3"].geometry}
          material={materials["Knit_Fleece_Terry_FRONT_109192.017"]}
        />
      </group>
      <group
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["30001_1"].geometry}
          material={materials["Knit_Fleece_Terry_FRONT_109192.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["30001_2"].geometry}
          material={materials["Knit_Fleece_Terry_FRONT_109192.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["30001_3"].geometry}
          material={materials["Knit_Fleece_Terry_FRONT_109192.005"]}
        />
      </group>
      <group
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["29001_1"].geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["29001_2"].geometry}
          material={materials["fuzz.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["29001_3"].geometry}
          material={materials["Knit_Fleece_Terry_FRONT_109192.014"]}
        />
      </group>
      <group
        position={[0.60390759, -0.96294826, -2.22966218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["28001_1"].geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["28001_2"].geometry}
          material={materials.fuzz}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["28001_3"].geometry}
          material={materials["Knit_Fleece_Terry_FRONT_109192.017"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/cr24tee1.glb");
